/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sx.icecap.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ActionHistory service. Represents a row in the &quot;SX_ICECAP_ActionHistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.sx.icecap.model.impl.ActionHistoryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.sx.icecap.model.impl.ActionHistoryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ActionHistory
 * @generated
 */
@ProviderType
public interface ActionHistoryModel extends BaseModel<ActionHistory> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a action history model instance should use the {@link ActionHistory} interface instead.
	 */

	/**
	 * Returns the primary key of this action history.
	 *
	 * @return the primary key of this action history
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this action history.
	 *
	 * @param primaryKey the primary key of this action history
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the action history ID of this action history.
	 *
	 * @return the action history ID of this action history
	 */
	public long getActionHistoryId();

	/**
	 * Sets the action history ID of this action history.
	 *
	 * @param actionHistoryId the action history ID of this action history
	 */
	public void setActionHistoryId(long actionHistoryId);

	/**
	 * Returns the user ID of this action history.
	 *
	 * @return the user ID of this action history
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this action history.
	 *
	 * @param userId the user ID of this action history
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this action history.
	 *
	 * @return the user uuid of this action history
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this action history.
	 *
	 * @param userUuid the user uuid of this action history
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this action history.
	 *
	 * @return the user name of this action history
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this action history.
	 *
	 * @param userName the user name of this action history
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this action history.
	 *
	 * @return the create date of this action history
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this action history.
	 *
	 * @param createDate the create date of this action history
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the action model of this action history.
	 *
	 * @return the action model of this action history
	 */
	@AutoEscape
	public String getActionModel();

	/**
	 * Sets the action model of this action history.
	 *
	 * @param actionModel the action model of this action history
	 */
	public void setActionModel(String actionModel);

	/**
	 * Returns the data ID of this action history.
	 *
	 * @return the data ID of this action history
	 */
	public long getDataId();

	/**
	 * Sets the data ID of this action history.
	 *
	 * @param dataId the data ID of this action history
	 */
	public void setDataId(long dataId);

	/**
	 * Returns the param code of this action history.
	 *
	 * @return the param code of this action history
	 */
	@AutoEscape
	public String getParamCode();

	/**
	 * Sets the param code of this action history.
	 *
	 * @param paramCode the param code of this action history
	 */
	public void setParamCode(String paramCode);

	/**
	 * Returns the action command of this action history.
	 *
	 * @return the action command of this action history
	 */
	@AutoEscape
	public String getActionCommand();

	/**
	 * Sets the action command of this action history.
	 *
	 * @param actionCommand the action command of this action history
	 */
	public void setActionCommand(String actionCommand);

	/**
	 * Returns the prev value of this action history.
	 *
	 * @return the prev value of this action history
	 */
	@AutoEscape
	public String getPrevValue();

	/**
	 * Sets the prev value of this action history.
	 *
	 * @param prevValue the prev value of this action history
	 */
	public void setPrevValue(String prevValue);

	/**
	 * Returns the modified value of this action history.
	 *
	 * @return the modified value of this action history
	 */
	@AutoEscape
	public String getModifiedValue();

	/**
	 * Sets the modified value of this action history.
	 *
	 * @param modifiedValue the modified value of this action history
	 */
	public void setModifiedValue(String modifiedValue);

	/**
	 * Returns the comment of this action history.
	 *
	 * @return the comment of this action history
	 */
	@AutoEscape
	public String getComment();

	/**
	 * Sets the comment of this action history.
	 *
	 * @param comment the comment of this action history
	 */
	public void setComment(String comment);

}