/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sx.icecap.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedGroupedModel;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DataComment service. Represents a row in the &quot;SX_ICECAP_DataComment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.sx.icecap.model.impl.DataCommentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.sx.icecap.model.impl.DataCommentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DataComment
 * @generated
 */
@ProviderType
public interface DataCommentModel
	extends BaseModel<DataComment>, ShardedModel, StagedGroupedModel,
			TrashedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a data comment model instance should use the {@link DataComment} interface instead.
	 */

	/**
	 * Returns the primary key of this data comment.
	 *
	 * @return the primary key of this data comment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this data comment.
	 *
	 * @param primaryKey the primary key of this data comment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this data comment.
	 *
	 * @return the uuid of this data comment
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this data comment.
	 *
	 * @param uuid the uuid of this data comment
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the data comment ID of this data comment.
	 *
	 * @return the data comment ID of this data comment
	 */
	public long getDataCommentId();

	/**
	 * Sets the data comment ID of this data comment.
	 *
	 * @param dataCommentId the data comment ID of this data comment
	 */
	public void setDataCommentId(long dataCommentId);

	/**
	 * Returns the company ID of this data comment.
	 *
	 * @return the company ID of this data comment
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this data comment.
	 *
	 * @param companyId the company ID of this data comment
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this data comment.
	 *
	 * @return the group ID of this data comment
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this data comment.
	 *
	 * @param groupId the group ID of this data comment
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this data comment.
	 *
	 * @return the user ID of this data comment
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this data comment.
	 *
	 * @param userId the user ID of this data comment
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this data comment.
	 *
	 * @return the user uuid of this data comment
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this data comment.
	 *
	 * @param userUuid the user uuid of this data comment
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this data comment.
	 *
	 * @return the user name of this data comment
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this data comment.
	 *
	 * @param userName the user name of this data comment
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this data comment.
	 *
	 * @return the create date of this data comment
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this data comment.
	 *
	 * @param createDate the create date of this data comment
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this data comment.
	 *
	 * @return the modified date of this data comment
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this data comment.
	 *
	 * @param modifiedDate the modified date of this data comment
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this data comment.
	 *
	 * @return the status of this data comment
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this data comment.
	 *
	 * @param status the status of this data comment
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this data comment.
	 *
	 * @return the status by user ID of this data comment
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this data comment.
	 *
	 * @param statusByUserId the status by user ID of this data comment
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this data comment.
	 *
	 * @return the status by user uuid of this data comment
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this data comment.
	 *
	 * @param statusByUserUuid the status by user uuid of this data comment
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this data comment.
	 *
	 * @return the status by user name of this data comment
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this data comment.
	 *
	 * @param statusByUserName the status by user name of this data comment
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this data comment.
	 *
	 * @return the status date of this data comment
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this data comment.
	 *
	 * @param statusDate the status date of this data comment
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the last publish date of this data comment.
	 *
	 * @return the last publish date of this data comment
	 */
	@Override
	public Date getLastPublishDate();

	/**
	 * Sets the last publish date of this data comment.
	 *
	 * @param lastPublishDate the last publish date of this data comment
	 */
	@Override
	public void setLastPublishDate(Date lastPublishDate);

	/**
	 * Returns the comment model of this data comment.
	 *
	 * @return the comment model of this data comment
	 */
	@AutoEscape
	public String getCommentModel();

	/**
	 * Sets the comment model of this data comment.
	 *
	 * @param commentModel the comment model of this data comment
	 */
	public void setCommentModel(String commentModel);

	/**
	 * Returns the data ID of this data comment.
	 *
	 * @return the data ID of this data comment
	 */
	public long getDataId();

	/**
	 * Sets the data ID of this data comment.
	 *
	 * @param dataId the data ID of this data comment
	 */
	public void setDataId(long dataId);

	/**
	 * Returns the param code of this data comment.
	 *
	 * @return the param code of this data comment
	 */
	@AutoEscape
	public String getParamCode();

	/**
	 * Sets the param code of this data comment.
	 *
	 * @param paramCode the param code of this data comment
	 */
	public void setParamCode(String paramCode);

	/**
	 * Returns the parent comment ID of this data comment.
	 *
	 * @return the parent comment ID of this data comment
	 */
	public long getParentCommentId();

	/**
	 * Sets the parent comment ID of this data comment.
	 *
	 * @param parentCommentId the parent comment ID of this data comment
	 */
	public void setParentCommentId(long parentCommentId);

	/**
	 * Returns the comment of this data comment.
	 *
	 * @return the comment of this data comment
	 */
	@AutoEscape
	public String getComment();

	/**
	 * Sets the comment of this data comment.
	 *
	 * @param comment the comment of this data comment
	 */
	public void setComment(String comment);

	/**
	 * Returns the trash entry created when this data comment was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this data comment.
	 *
	 * @return the trash entry created when this data comment was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this data comment.
	 *
	 * @return the class primary key of the trash entry for this data comment
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this data comment.
	 *
	 * @return the trash handler for this data comment
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this data comment is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this data comment is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this data comment is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this data comment is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

	/**
	 * Returns <code>true</code> if this data comment is approved.
	 *
	 * @return <code>true</code> if this data comment is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this data comment is denied.
	 *
	 * @return <code>true</code> if this data comment is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this data comment is a draft.
	 *
	 * @return <code>true</code> if this data comment is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this data comment is expired.
	 *
	 * @return <code>true</code> if this data comment is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this data comment is inactive.
	 *
	 * @return <code>true</code> if this data comment is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this data comment is incomplete.
	 *
	 * @return <code>true</code> if this data comment is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this data comment is pending.
	 *
	 * @return <code>true</code> if this data comment is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this data comment is scheduled.
	 *
	 * @return <code>true</code> if this data comment is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}