/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sx.icecap.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedGroupedModel;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Parameter service. Represents a row in the &quot;SX_ICECAP_Parameter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.sx.icecap.model.impl.ParameterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.sx.icecap.model.impl.ParameterImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Parameter
 * @generated
 */
@ProviderType
public interface ParameterModel
	extends BaseModel<Parameter>, LocalizedModel, ShardedModel,
			StagedGroupedModel, TrashedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a parameter model instance should use the {@link Parameter} interface instead.
	 */

	/**
	 * Returns the primary key of this parameter.
	 *
	 * @return the primary key of this parameter
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this parameter.
	 *
	 * @param primaryKey the primary key of this parameter
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this parameter.
	 *
	 * @return the uuid of this parameter
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this parameter.
	 *
	 * @param uuid the uuid of this parameter
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the parameter ID of this parameter.
	 *
	 * @return the parameter ID of this parameter
	 */
	public long getParameterId();

	/**
	 * Sets the parameter ID of this parameter.
	 *
	 * @param parameterId the parameter ID of this parameter
	 */
	public void setParameterId(long parameterId);

	/**
	 * Returns the group parameter ID of this parameter.
	 *
	 * @return the group parameter ID of this parameter
	 */
	@AutoEscape
	public String getGroupParameterId();

	/**
	 * Sets the group parameter ID of this parameter.
	 *
	 * @param groupParameterId the group parameter ID of this parameter
	 */
	public void setGroupParameterId(String groupParameterId);

	/**
	 * Returns the group ID of this parameter.
	 *
	 * @return the group ID of this parameter
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this parameter.
	 *
	 * @param groupId the group ID of this parameter
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this parameter.
	 *
	 * @return the company ID of this parameter
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this parameter.
	 *
	 * @param companyId the company ID of this parameter
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this parameter.
	 *
	 * @return the user ID of this parameter
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this parameter.
	 *
	 * @param userId the user ID of this parameter
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this parameter.
	 *
	 * @return the user uuid of this parameter
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this parameter.
	 *
	 * @param userUuid the user uuid of this parameter
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this parameter.
	 *
	 * @return the user name of this parameter
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this parameter.
	 *
	 * @param userName the user name of this parameter
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this parameter.
	 *
	 * @return the create date of this parameter
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this parameter.
	 *
	 * @param createDate the create date of this parameter
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this parameter.
	 *
	 * @return the modified date of this parameter
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this parameter.
	 *
	 * @param modifiedDate the modified date of this parameter
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this parameter.
	 *
	 * @return the status of this parameter
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this parameter.
	 *
	 * @param status the status of this parameter
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this parameter.
	 *
	 * @return the status by user ID of this parameter
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this parameter.
	 *
	 * @param statusByUserId the status by user ID of this parameter
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this parameter.
	 *
	 * @return the status by user uuid of this parameter
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this parameter.
	 *
	 * @param statusByUserUuid the status by user uuid of this parameter
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this parameter.
	 *
	 * @return the status by user name of this parameter
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this parameter.
	 *
	 * @param statusByUserName the status by user name of this parameter
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this parameter.
	 *
	 * @return the status date of this parameter
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this parameter.
	 *
	 * @param statusDate the status date of this parameter
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the last publish date of this parameter.
	 *
	 * @return the last publish date of this parameter
	 */
	@Override
	public Date getLastPublishDate();

	/**
	 * Sets the last publish date of this parameter.
	 *
	 * @param lastPublishDate the last publish date of this parameter
	 */
	@Override
	public void setLastPublishDate(Date lastPublishDate);

	/**
	 * Returns the param name of this parameter.
	 *
	 * @return the param name of this parameter
	 */
	@AutoEscape
	public String getParamName();

	/**
	 * Sets the param name of this parameter.
	 *
	 * @param paramName the param name of this parameter
	 */
	public void setParamName(String paramName);

	/**
	 * Returns the param version of this parameter.
	 *
	 * @return the param version of this parameter
	 */
	@AutoEscape
	public String getParamVersion();

	/**
	 * Sets the param version of this parameter.
	 *
	 * @param paramVersion the param version of this parameter
	 */
	public void setParamVersion(String paramVersion);

	/**
	 * Returns the param type of this parameter.
	 *
	 * @return the param type of this parameter
	 */
	@AutoEscape
	public String getParamType();

	/**
	 * Sets the param type of this parameter.
	 *
	 * @param paramType the param type of this parameter
	 */
	public void setParamType(String paramType);

	/**
	 * Returns the display name of this parameter.
	 *
	 * @return the display name of this parameter
	 */
	public String getDisplayName();

	/**
	 * Returns the localized display name of this parameter in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized display name of this parameter
	 */
	@AutoEscape
	public String getDisplayName(Locale locale);

	/**
	 * Returns the localized display name of this parameter in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized display name of this parameter. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDisplayName(Locale locale, boolean useDefault);

	/**
	 * Returns the localized display name of this parameter in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized display name of this parameter
	 */
	@AutoEscape
	public String getDisplayName(String languageId);

	/**
	 * Returns the localized display name of this parameter in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized display name of this parameter
	 */
	@AutoEscape
	public String getDisplayName(String languageId, boolean useDefault);

	@AutoEscape
	public String getDisplayNameCurrentLanguageId();

	@AutoEscape
	public String getDisplayNameCurrentValue();

	/**
	 * Returns a map of the locales and localized display names of this parameter.
	 *
	 * @return the locales and localized display names of this parameter
	 */
	public Map<Locale, String> getDisplayNameMap();

	/**
	 * Sets the display name of this parameter.
	 *
	 * @param displayName the display name of this parameter
	 */
	public void setDisplayName(String displayName);

	/**
	 * Sets the localized display name of this parameter in the language.
	 *
	 * @param displayName the localized display name of this parameter
	 * @param locale the locale of the language
	 */
	public void setDisplayName(String displayName, Locale locale);

	/**
	 * Sets the localized display name of this parameter in the language, and sets the default locale.
	 *
	 * @param displayName the localized display name of this parameter
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDisplayName(
		String displayName, Locale locale, Locale defaultLocale);

	public void setDisplayNameCurrentLanguageId(String languageId);

	/**
	 * Sets the localized display names of this parameter from the map of locales and localized display names.
	 *
	 * @param displayNameMap the locales and localized display names of this parameter
	 */
	public void setDisplayNameMap(Map<Locale, String> displayNameMap);

	/**
	 * Sets the localized display names of this parameter from the map of locales and localized display names, and sets the default locale.
	 *
	 * @param displayNameMap the locales and localized display names of this parameter
	 * @param defaultLocale the default locale
	 */
	public void setDisplayNameMap(
		Map<Locale, String> displayNameMap, Locale defaultLocale);

	/**
	 * Returns the definition of this parameter.
	 *
	 * @return the definition of this parameter
	 */
	public String getDefinition();

	/**
	 * Returns the localized definition of this parameter in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized definition of this parameter
	 */
	@AutoEscape
	public String getDefinition(Locale locale);

	/**
	 * Returns the localized definition of this parameter in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized definition of this parameter. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDefinition(Locale locale, boolean useDefault);

	/**
	 * Returns the localized definition of this parameter in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized definition of this parameter
	 */
	@AutoEscape
	public String getDefinition(String languageId);

	/**
	 * Returns the localized definition of this parameter in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized definition of this parameter
	 */
	@AutoEscape
	public String getDefinition(String languageId, boolean useDefault);

	@AutoEscape
	public String getDefinitionCurrentLanguageId();

	@AutoEscape
	public String getDefinitionCurrentValue();

	/**
	 * Returns a map of the locales and localized definitions of this parameter.
	 *
	 * @return the locales and localized definitions of this parameter
	 */
	public Map<Locale, String> getDefinitionMap();

	/**
	 * Sets the definition of this parameter.
	 *
	 * @param definition the definition of this parameter
	 */
	public void setDefinition(String definition);

	/**
	 * Sets the localized definition of this parameter in the language.
	 *
	 * @param definition the localized definition of this parameter
	 * @param locale the locale of the language
	 */
	public void setDefinition(String definition, Locale locale);

	/**
	 * Sets the localized definition of this parameter in the language, and sets the default locale.
	 *
	 * @param definition the localized definition of this parameter
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDefinition(
		String definition, Locale locale, Locale defaultLocale);

	public void setDefinitionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized definitions of this parameter from the map of locales and localized definitions.
	 *
	 * @param definitionMap the locales and localized definitions of this parameter
	 */
	public void setDefinitionMap(Map<Locale, String> definitionMap);

	/**
	 * Sets the localized definitions of this parameter from the map of locales and localized definitions, and sets the default locale.
	 *
	 * @param definitionMap the locales and localized definitions of this parameter
	 * @param defaultLocale the default locale
	 */
	public void setDefinitionMap(
		Map<Locale, String> definitionMap, Locale defaultLocale);

	/**
	 * Returns the tooltip of this parameter.
	 *
	 * @return the tooltip of this parameter
	 */
	public String getTooltip();

	/**
	 * Returns the localized tooltip of this parameter in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized tooltip of this parameter
	 */
	@AutoEscape
	public String getTooltip(Locale locale);

	/**
	 * Returns the localized tooltip of this parameter in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized tooltip of this parameter. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getTooltip(Locale locale, boolean useDefault);

	/**
	 * Returns the localized tooltip of this parameter in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized tooltip of this parameter
	 */
	@AutoEscape
	public String getTooltip(String languageId);

	/**
	 * Returns the localized tooltip of this parameter in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized tooltip of this parameter
	 */
	@AutoEscape
	public String getTooltip(String languageId, boolean useDefault);

	@AutoEscape
	public String getTooltipCurrentLanguageId();

	@AutoEscape
	public String getTooltipCurrentValue();

	/**
	 * Returns a map of the locales and localized tooltips of this parameter.
	 *
	 * @return the locales and localized tooltips of this parameter
	 */
	public Map<Locale, String> getTooltipMap();

	/**
	 * Sets the tooltip of this parameter.
	 *
	 * @param tooltip the tooltip of this parameter
	 */
	public void setTooltip(String tooltip);

	/**
	 * Sets the localized tooltip of this parameter in the language.
	 *
	 * @param tooltip the localized tooltip of this parameter
	 * @param locale the locale of the language
	 */
	public void setTooltip(String tooltip, Locale locale);

	/**
	 * Sets the localized tooltip of this parameter in the language, and sets the default locale.
	 *
	 * @param tooltip the localized tooltip of this parameter
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setTooltip(String tooltip, Locale locale, Locale defaultLocale);

	public void setTooltipCurrentLanguageId(String languageId);

	/**
	 * Sets the localized tooltips of this parameter from the map of locales and localized tooltips.
	 *
	 * @param tooltipMap the locales and localized tooltips of this parameter
	 */
	public void setTooltipMap(Map<Locale, String> tooltipMap);

	/**
	 * Sets the localized tooltips of this parameter from the map of locales and localized tooltips, and sets the default locale.
	 *
	 * @param tooltipMap the locales and localized tooltips of this parameter
	 * @param defaultLocale the default locale
	 */
	public void setTooltipMap(
		Map<Locale, String> tooltipMap, Locale defaultLocale);

	/**
	 * Returns the synonyms of this parameter.
	 *
	 * @return the synonyms of this parameter
	 */
	@AutoEscape
	public String getSynonyms();

	/**
	 * Sets the synonyms of this parameter.
	 *
	 * @param synonyms the synonyms of this parameter
	 */
	public void setSynonyms(String synonyms);

	/**
	 * Returns the attributes json of this parameter.
	 *
	 * @return the attributes json of this parameter
	 */
	@AutoEscape
	public String getAttributesJSON();

	/**
	 * Sets the attributes json of this parameter.
	 *
	 * @param attributesJSON the attributes json of this parameter
	 */
	public void setAttributesJSON(String attributesJSON);

	/**
	 * Returns the standard of this parameter.
	 *
	 * @return the standard of this parameter
	 */
	public boolean getStandard();

	/**
	 * Returns <code>true</code> if this parameter is standard.
	 *
	 * @return <code>true</code> if this parameter is standard; <code>false</code> otherwise
	 */
	public boolean isStandard();

	/**
	 * Sets whether this parameter is standard.
	 *
	 * @param standard the standard of this parameter
	 */
	public void setStandard(boolean standard);

	/**
	 * Returns the trash entry created when this parameter was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this parameter.
	 *
	 * @return the trash entry created when this parameter was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this parameter.
	 *
	 * @return the class primary key of the trash entry for this parameter
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this parameter.
	 *
	 * @return the trash handler for this parameter
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this parameter is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this parameter is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this parameter is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this parameter is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

	/**
	 * Returns <code>true</code> if this parameter is approved.
	 *
	 * @return <code>true</code> if this parameter is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this parameter is denied.
	 *
	 * @return <code>true</code> if this parameter is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this parameter is a draft.
	 *
	 * @return <code>true</code> if this parameter is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this parameter is expired.
	 *
	 * @return <code>true</code> if this parameter is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this parameter is inactive.
	 *
	 * @return <code>true</code> if this parameter is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this parameter is incomplete.
	 *
	 * @return <code>true</code> if this parameter is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this parameter is pending.
	 *
	 * @return <code>true</code> if this parameter is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this parameter is scheduled.
	 *
	 * @return <code>true</code> if this parameter is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

}