/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sx.icecap.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TypeStructureLink service. Represents a row in the &quot;SX_ICECAP_TypeStructureLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.sx.icecap.model.impl.TypeStructureLinkModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.sx.icecap.model.impl.TypeStructureLinkImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TypeStructureLink
 * @generated
 */
@ProviderType
public interface TypeStructureLinkModel extends BaseModel<TypeStructureLink> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a type structure link model instance should use the {@link TypeStructureLink} interface instead.
	 */

	/**
	 * Returns the primary key of this type structure link.
	 *
	 * @return the primary key of this type structure link
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this type structure link.
	 *
	 * @param primaryKey the primary key of this type structure link
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the data type ID of this type structure link.
	 *
	 * @return the data type ID of this type structure link
	 */
	public long getDataTypeId();

	/**
	 * Sets the data type ID of this type structure link.
	 *
	 * @param dataTypeId the data type ID of this type structure link
	 */
	public void setDataTypeId(long dataTypeId);

	/**
	 * Returns the user ID of this type structure link.
	 *
	 * @return the user ID of this type structure link
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this type structure link.
	 *
	 * @param userId the user ID of this type structure link
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this type structure link.
	 *
	 * @return the user uuid of this type structure link
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this type structure link.
	 *
	 * @param userUuid the user uuid of this type structure link
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this type structure link.
	 *
	 * @return the group ID of this type structure link
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this type structure link.
	 *
	 * @param groupId the group ID of this type structure link
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the data structure ID of this type structure link.
	 *
	 * @return the data structure ID of this type structure link
	 */
	public long getDataStructureId();

	/**
	 * Sets the data structure ID of this type structure link.
	 *
	 * @param dataStructureId the data structure ID of this type structure link
	 */
	public void setDataStructureId(long dataStructureId);

	/**
	 * Returns the commentable of this type structure link.
	 *
	 * @return the commentable of this type structure link
	 */
	public boolean getCommentable();

	/**
	 * Returns <code>true</code> if this type structure link is commentable.
	 *
	 * @return <code>true</code> if this type structure link is commentable; <code>false</code> otherwise
	 */
	public boolean isCommentable();

	/**
	 * Sets whether this type structure link is commentable.
	 *
	 * @param commentable the commentable of this type structure link
	 */
	public void setCommentable(boolean commentable);

	/**
	 * Returns the verifiable of this type structure link.
	 *
	 * @return the verifiable of this type structure link
	 */
	public boolean getVerifiable();

	/**
	 * Returns <code>true</code> if this type structure link is verifiable.
	 *
	 * @return <code>true</code> if this type structure link is verifiable; <code>false</code> otherwise
	 */
	public boolean isVerifiable();

	/**
	 * Sets whether this type structure link is verifiable.
	 *
	 * @param verifiable the verifiable of this type structure link
	 */
	public void setVerifiable(boolean verifiable);

	/**
	 * Returns the freezable of this type structure link.
	 *
	 * @return the freezable of this type structure link
	 */
	public boolean getFreezable();

	/**
	 * Returns <code>true</code> if this type structure link is freezable.
	 *
	 * @return <code>true</code> if this type structure link is freezable; <code>false</code> otherwise
	 */
	public boolean isFreezable();

	/**
	 * Sets whether this type structure link is freezable.
	 *
	 * @param freezable the freezable of this type structure link
	 */
	public void setFreezable(boolean freezable);

	/**
	 * Returns the freezed of this type structure link.
	 *
	 * @return the freezed of this type structure link
	 */
	public boolean getFreezed();

	/**
	 * Returns <code>true</code> if this type structure link is freezed.
	 *
	 * @return <code>true</code> if this type structure link is freezed; <code>false</code> otherwise
	 */
	public boolean isFreezed();

	/**
	 * Sets whether this type structure link is freezed.
	 *
	 * @param freezed the freezed of this type structure link
	 */
	public void setFreezed(boolean freezed);

	/**
	 * Returns the freezed user ID of this type structure link.
	 *
	 * @return the freezed user ID of this type structure link
	 */
	public long getFreezedUserId();

	/**
	 * Sets the freezed user ID of this type structure link.
	 *
	 * @param freezedUserId the freezed user ID of this type structure link
	 */
	public void setFreezedUserId(long freezedUserId);

	/**
	 * Returns the freezed user uuid of this type structure link.
	 *
	 * @return the freezed user uuid of this type structure link
	 */
	public String getFreezedUserUuid();

	/**
	 * Sets the freezed user uuid of this type structure link.
	 *
	 * @param freezedUserUuid the freezed user uuid of this type structure link
	 */
	public void setFreezedUserUuid(String freezedUserUuid);

	/**
	 * Returns the freezed user name of this type structure link.
	 *
	 * @return the freezed user name of this type structure link
	 */
	@AutoEscape
	public String getFreezedUserName();

	/**
	 * Sets the freezed user name of this type structure link.
	 *
	 * @param freezedUserName the freezed user name of this type structure link
	 */
	public void setFreezedUserName(String freezedUserName);

	/**
	 * Returns the freezed date of this type structure link.
	 *
	 * @return the freezed date of this type structure link
	 */
	public Date getFreezedDate();

	/**
	 * Sets the freezed date of this type structure link.
	 *
	 * @param freezedDate the freezed date of this type structure link
	 */
	public void setFreezedDate(Date freezedDate);

	/**
	 * Returns the verified of this type structure link.
	 *
	 * @return the verified of this type structure link
	 */
	public boolean getVerified();

	/**
	 * Returns <code>true</code> if this type structure link is verified.
	 *
	 * @return <code>true</code> if this type structure link is verified; <code>false</code> otherwise
	 */
	public boolean isVerified();

	/**
	 * Sets whether this type structure link is verified.
	 *
	 * @param verified the verified of this type structure link
	 */
	public void setVerified(boolean verified);

	/**
	 * Returns the verified user ID of this type structure link.
	 *
	 * @return the verified user ID of this type structure link
	 */
	public long getVerifiedUserId();

	/**
	 * Sets the verified user ID of this type structure link.
	 *
	 * @param verifiedUserId the verified user ID of this type structure link
	 */
	public void setVerifiedUserId(long verifiedUserId);

	/**
	 * Returns the verified user uuid of this type structure link.
	 *
	 * @return the verified user uuid of this type structure link
	 */
	public String getVerifiedUserUuid();

	/**
	 * Sets the verified user uuid of this type structure link.
	 *
	 * @param verifiedUserUuid the verified user uuid of this type structure link
	 */
	public void setVerifiedUserUuid(String verifiedUserUuid);

	/**
	 * Returns the verified user name of this type structure link.
	 *
	 * @return the verified user name of this type structure link
	 */
	@AutoEscape
	public String getVerifiedUserName();

	/**
	 * Sets the verified user name of this type structure link.
	 *
	 * @param verifiedUserName the verified user name of this type structure link
	 */
	public void setVerifiedUserName(String verifiedUserName);

	/**
	 * Returns the verified date of this type structure link.
	 *
	 * @return the verified date of this type structure link
	 */
	public Date getVerifiedDate();

	/**
	 * Sets the verified date of this type structure link.
	 *
	 * @param verifiedDate the verified date of this type structure link
	 */
	public void setVerifiedDate(Date verifiedDate);

	/**
	 * Returns the input status of this type structure link.
	 *
	 * @return the input status of this type structure link
	 */
	public boolean getInputStatus();

	/**
	 * Returns <code>true</code> if this type structure link is input status.
	 *
	 * @return <code>true</code> if this type structure link is input status; <code>false</code> otherwise
	 */
	public boolean isInputStatus();

	/**
	 * Sets whether this type structure link is input status.
	 *
	 * @param inputStatus the input status of this type structure link
	 */
	public void setInputStatus(boolean inputStatus);

	/**
	 * Returns the jump to of this type structure link.
	 *
	 * @return the jump to of this type structure link
	 */
	public boolean getJumpTo();

	/**
	 * Returns <code>true</code> if this type structure link is jump to.
	 *
	 * @return <code>true</code> if this type structure link is jump to; <code>false</code> otherwise
	 */
	public boolean isJumpTo();

	/**
	 * Sets whether this type structure link is jump to.
	 *
	 * @param jumpTo the jump to of this type structure link
	 */
	public void setJumpTo(boolean jumpTo);

}