/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.sx.icecap.model.impl;

import com.sx.icecap.model.ActionHistory;
import com.sx.icecap.service.ActionHistoryLocalServiceUtil;

/**
 * The extended model base implementation for the ActionHistory service. Represents a row in the &quot;SX_ICECAP_ActionHistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ActionHistoryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ActionHistoryImpl
 * @see ActionHistory
 * @generated
 */
public abstract class ActionHistoryBaseImpl
	extends ActionHistoryModelImpl implements ActionHistory {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a action history model instance should use the <code>ActionHistory</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ActionHistoryLocalServiceUtil.addActionHistory(this);
		}
		else {
			ActionHistoryLocalServiceUtil.updateActionHistory(this);
		}
	}

}