/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sx.icecap.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.sx.icecap.model.CollectionSetLink;
import com.sx.icecap.model.CollectionSetLinkModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CollectionSetLink service. Represents a row in the &quot;SX_ICECAP_CollectionSetLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CollectionSetLinkModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CollectionSetLinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CollectionSetLinkImpl
 * @generated
 */
public class CollectionSetLinkModelImpl
	extends BaseModelImpl<CollectionSetLink> implements CollectionSetLinkModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a collection set link model instance should use the <code>CollectionSetLink</code> interface instead.
	 */
	public static final String TABLE_NAME = "SX_ICECAP_CollectionSetLink";

	public static final Object[][] TABLE_COLUMNS = {
		{"collectionSetLinkId", Types.BIGINT},
		{"dataCollectionId", Types.BIGINT}, {"dataCollection", Types.BIGINT},
		{"dataSetId", Types.BIGINT}, {"dataSet", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("collectionSetLinkId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataCollection", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataSetId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataSet", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SX_ICECAP_CollectionSetLink (collectionSetLinkId LONG not null primary key,dataCollectionId LONG,dataCollection LONG,dataSetId LONG,dataSet LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table SX_ICECAP_CollectionSetLink";

	public static final String ORDER_BY_JPQL =
		" ORDER BY collectionSetLink.collectionSetLinkId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SX_ICECAP_CollectionSetLink.collectionSetLinkId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long DATACOLLECTIONID_COLUMN_BITMASK = 1L;

	public static final long DATASETID_COLUMN_BITMASK = 2L;

	public static final long COLLECTIONSETLINKID_COLUMN_BITMASK = 4L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public CollectionSetLinkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _collectionSetLinkId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCollectionSetLinkId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _collectionSetLinkId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CollectionSetLink.class;
	}

	@Override
	public String getModelClassName() {
		return CollectionSetLink.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CollectionSetLink, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CollectionSetLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CollectionSetLink, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CollectionSetLink)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CollectionSetLink, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CollectionSetLink, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CollectionSetLink)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CollectionSetLink, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CollectionSetLink, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<CollectionSetLink, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CollectionSetLink, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CollectionSetLink, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<CollectionSetLink, Object>>();
		Map<String, BiConsumer<CollectionSetLink, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<CollectionSetLink, ?>>();

		attributeGetterFunctions.put(
			"collectionSetLinkId", CollectionSetLink::getCollectionSetLinkId);
		attributeSetterBiConsumers.put(
			"collectionSetLinkId",
			(BiConsumer<CollectionSetLink, Long>)
				CollectionSetLink::setCollectionSetLinkId);
		attributeGetterFunctions.put(
			"dataCollectionId", CollectionSetLink::getDataCollectionId);
		attributeSetterBiConsumers.put(
			"dataCollectionId",
			(BiConsumer<CollectionSetLink, Long>)
				CollectionSetLink::setDataCollectionId);
		attributeGetterFunctions.put(
			"dataCollection", CollectionSetLink::getDataCollection);
		attributeSetterBiConsumers.put(
			"dataCollection",
			(BiConsumer<CollectionSetLink, Long>)
				CollectionSetLink::setDataCollection);
		attributeGetterFunctions.put(
			"dataSetId", CollectionSetLink::getDataSetId);
		attributeSetterBiConsumers.put(
			"dataSetId",
			(BiConsumer<CollectionSetLink, Long>)
				CollectionSetLink::setDataSetId);
		attributeGetterFunctions.put("dataSet", CollectionSetLink::getDataSet);
		attributeSetterBiConsumers.put(
			"dataSet",
			(BiConsumer<CollectionSetLink, Long>)CollectionSetLink::setDataSet);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getCollectionSetLinkId() {
		return _collectionSetLinkId;
	}

	@Override
	public void setCollectionSetLinkId(long collectionSetLinkId) {
		_collectionSetLinkId = collectionSetLinkId;
	}

	@Override
	public long getDataCollectionId() {
		return _dataCollectionId;
	}

	@Override
	public void setDataCollectionId(long dataCollectionId) {
		_columnBitmask |= DATACOLLECTIONID_COLUMN_BITMASK;

		if (!_setOriginalDataCollectionId) {
			_setOriginalDataCollectionId = true;

			_originalDataCollectionId = _dataCollectionId;
		}

		_dataCollectionId = dataCollectionId;
	}

	public long getOriginalDataCollectionId() {
		return _originalDataCollectionId;
	}

	@Override
	public long getDataCollection() {
		return _dataCollection;
	}

	@Override
	public void setDataCollection(long dataCollection) {
		_dataCollection = dataCollection;
	}

	@Override
	public long getDataSetId() {
		return _dataSetId;
	}

	@Override
	public void setDataSetId(long dataSetId) {
		_columnBitmask |= DATASETID_COLUMN_BITMASK;

		if (!_setOriginalDataSetId) {
			_setOriginalDataSetId = true;

			_originalDataSetId = _dataSetId;
		}

		_dataSetId = dataSetId;
	}

	public long getOriginalDataSetId() {
		return _originalDataSetId;
	}

	@Override
	public long getDataSet() {
		return _dataSet;
	}

	@Override
	public void setDataSet(long dataSet) {
		_dataSet = dataSet;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, CollectionSetLink.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CollectionSetLink toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CollectionSetLink>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CollectionSetLinkImpl collectionSetLinkImpl =
			new CollectionSetLinkImpl();

		collectionSetLinkImpl.setCollectionSetLinkId(getCollectionSetLinkId());
		collectionSetLinkImpl.setDataCollectionId(getDataCollectionId());
		collectionSetLinkImpl.setDataCollection(getDataCollection());
		collectionSetLinkImpl.setDataSetId(getDataSetId());
		collectionSetLinkImpl.setDataSet(getDataSet());

		collectionSetLinkImpl.resetOriginalValues();

		return collectionSetLinkImpl;
	}

	@Override
	public int compareTo(CollectionSetLink collectionSetLink) {
		long primaryKey = collectionSetLink.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CollectionSetLink)) {
			return false;
		}

		CollectionSetLink collectionSetLink = (CollectionSetLink)object;

		long primaryKey = collectionSetLink.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalDataCollectionId = _dataCollectionId;

		_setOriginalDataCollectionId = false;

		_originalDataSetId = _dataSetId;

		_setOriginalDataSetId = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CollectionSetLink> toCacheModel() {
		CollectionSetLinkCacheModel collectionSetLinkCacheModel =
			new CollectionSetLinkCacheModel();

		collectionSetLinkCacheModel.collectionSetLinkId =
			getCollectionSetLinkId();

		collectionSetLinkCacheModel.dataCollectionId = getDataCollectionId();

		collectionSetLinkCacheModel.dataCollection = getDataCollection();

		collectionSetLinkCacheModel.dataSetId = getDataSetId();

		collectionSetLinkCacheModel.dataSet = getDataSet();

		return collectionSetLinkCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CollectionSetLink, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CollectionSetLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CollectionSetLink, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(CollectionSetLink)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CollectionSetLink, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CollectionSetLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CollectionSetLink, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CollectionSetLink)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CollectionSetLink>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					CollectionSetLink.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _collectionSetLinkId;
	private long _dataCollectionId;
	private long _originalDataCollectionId;
	private boolean _setOriginalDataCollectionId;
	private long _dataCollection;
	private long _dataSetId;
	private long _originalDataSetId;
	private boolean _setOriginalDataSetId;
	private long _dataSet;
	private long _columnBitmask;
	private CollectionSetLink _escapedModel;

}