/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sx.icecap.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.sx.icecap.model.CollectionSetLink;
import com.sx.icecap.model.CollectionSetLinkModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CollectionSetLink service. Represents a row in the &quot;SX_ICECAP_CollectionSetLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CollectionSetLinkModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CollectionSetLinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CollectionSetLinkImpl
 * @generated
 */
public class CollectionSetLinkModelImpl
	extends BaseModelImpl<CollectionSetLink> implements CollectionSetLinkModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a collection set link model instance should use the <code>CollectionSetLink</code> interface instead.
	 */
	public static final String TABLE_NAME = "SX_ICECAP_CollectionSetLink";

	public static final Object[][] TABLE_COLUMNS = {
		{"companyId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"collectionSetLinkId", Types.BIGINT},
		{"dataCollectionId", Types.BIGINT}, {"dataSetId", Types.BIGINT},
		{"order_", Types.INTEGER}, {"commentable", Types.BOOLEAN},
		{"verifiable", Types.BOOLEAN}, {"freezable", Types.BOOLEAN},
		{"freezed", Types.BOOLEAN}, {"freezedUserId", Types.BIGINT},
		{"freezedUserName", Types.VARCHAR}, {"freezedDate", Types.TIMESTAMP},
		{"verified", Types.BOOLEAN}, {"verifiedUserId", Types.BIGINT},
		{"verifiedUserName", Types.VARCHAR}, {"verifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("collectionSetLinkId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataSetId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("order_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("commentable", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("verifiable", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("freezable", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("freezed", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("freezedUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("freezedUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("freezedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("verified", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("verifiedUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("verifiedUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("verifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SX_ICECAP_CollectionSetLink (companyId LONG,groupId LONG,collectionSetLinkId LONG not null primary key,dataCollectionId LONG,dataSetId LONG,order_ INTEGER,commentable BOOLEAN,verifiable BOOLEAN,freezable BOOLEAN,freezed BOOLEAN,freezedUserId LONG,freezedUserName VARCHAR(75) null,freezedDate DATE null,verified BOOLEAN,verifiedUserId LONG,verifiedUserName VARCHAR(75) null,verifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table SX_ICECAP_CollectionSetLink";

	public static final String ORDER_BY_JPQL =
		" ORDER BY collectionSetLink.collectionSetLinkId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SX_ICECAP_CollectionSetLink.collectionSetLinkId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long DATACOLLECTIONID_COLUMN_BITMASK = 1L;

	public static final long DATASETID_COLUMN_BITMASK = 2L;

	public static final long GROUPID_COLUMN_BITMASK = 4L;

	public static final long COLLECTIONSETLINKID_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public CollectionSetLinkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _collectionSetLinkId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCollectionSetLinkId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _collectionSetLinkId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CollectionSetLink.class;
	}

	@Override
	public String getModelClassName() {
		return CollectionSetLink.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CollectionSetLink, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CollectionSetLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CollectionSetLink, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CollectionSetLink)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CollectionSetLink, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CollectionSetLink, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CollectionSetLink)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CollectionSetLink, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CollectionSetLink, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<CollectionSetLink, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CollectionSetLink, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CollectionSetLink, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<CollectionSetLink, Object>>();
		Map<String, BiConsumer<CollectionSetLink, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<CollectionSetLink, ?>>();

		attributeGetterFunctions.put(
			"companyId", CollectionSetLink::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<CollectionSetLink, Long>)
				CollectionSetLink::setCompanyId);
		attributeGetterFunctions.put("groupId", CollectionSetLink::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<CollectionSetLink, Long>)CollectionSetLink::setGroupId);
		attributeGetterFunctions.put(
			"collectionSetLinkId", CollectionSetLink::getCollectionSetLinkId);
		attributeSetterBiConsumers.put(
			"collectionSetLinkId",
			(BiConsumer<CollectionSetLink, Long>)
				CollectionSetLink::setCollectionSetLinkId);
		attributeGetterFunctions.put(
			"dataCollectionId", CollectionSetLink::getDataCollectionId);
		attributeSetterBiConsumers.put(
			"dataCollectionId",
			(BiConsumer<CollectionSetLink, Long>)
				CollectionSetLink::setDataCollectionId);
		attributeGetterFunctions.put(
			"dataSetId", CollectionSetLink::getDataSetId);
		attributeSetterBiConsumers.put(
			"dataSetId",
			(BiConsumer<CollectionSetLink, Long>)
				CollectionSetLink::setDataSetId);
		attributeGetterFunctions.put("order", CollectionSetLink::getOrder);
		attributeSetterBiConsumers.put(
			"order",
			(BiConsumer<CollectionSetLink, Integer>)
				CollectionSetLink::setOrder);
		attributeGetterFunctions.put(
			"commentable", CollectionSetLink::getCommentable);
		attributeSetterBiConsumers.put(
			"commentable",
			(BiConsumer<CollectionSetLink, Boolean>)
				CollectionSetLink::setCommentable);
		attributeGetterFunctions.put(
			"verifiable", CollectionSetLink::getVerifiable);
		attributeSetterBiConsumers.put(
			"verifiable",
			(BiConsumer<CollectionSetLink, Boolean>)
				CollectionSetLink::setVerifiable);
		attributeGetterFunctions.put(
			"freezable", CollectionSetLink::getFreezable);
		attributeSetterBiConsumers.put(
			"freezable",
			(BiConsumer<CollectionSetLink, Boolean>)
				CollectionSetLink::setFreezable);
		attributeGetterFunctions.put("freezed", CollectionSetLink::getFreezed);
		attributeSetterBiConsumers.put(
			"freezed",
			(BiConsumer<CollectionSetLink, Boolean>)
				CollectionSetLink::setFreezed);
		attributeGetterFunctions.put(
			"freezedUserId", CollectionSetLink::getFreezedUserId);
		attributeSetterBiConsumers.put(
			"freezedUserId",
			(BiConsumer<CollectionSetLink, Long>)
				CollectionSetLink::setFreezedUserId);
		attributeGetterFunctions.put(
			"freezedUserName", CollectionSetLink::getFreezedUserName);
		attributeSetterBiConsumers.put(
			"freezedUserName",
			(BiConsumer<CollectionSetLink, String>)
				CollectionSetLink::setFreezedUserName);
		attributeGetterFunctions.put(
			"freezedDate", CollectionSetLink::getFreezedDate);
		attributeSetterBiConsumers.put(
			"freezedDate",
			(BiConsumer<CollectionSetLink, Date>)
				CollectionSetLink::setFreezedDate);
		attributeGetterFunctions.put(
			"verified", CollectionSetLink::getVerified);
		attributeSetterBiConsumers.put(
			"verified",
			(BiConsumer<CollectionSetLink, Boolean>)
				CollectionSetLink::setVerified);
		attributeGetterFunctions.put(
			"verifiedUserId", CollectionSetLink::getVerifiedUserId);
		attributeSetterBiConsumers.put(
			"verifiedUserId",
			(BiConsumer<CollectionSetLink, Long>)
				CollectionSetLink::setVerifiedUserId);
		attributeGetterFunctions.put(
			"verifiedUserName", CollectionSetLink::getVerifiedUserName);
		attributeSetterBiConsumers.put(
			"verifiedUserName",
			(BiConsumer<CollectionSetLink, String>)
				CollectionSetLink::setVerifiedUserName);
		attributeGetterFunctions.put(
			"verifiedDate", CollectionSetLink::getVerifiedDate);
		attributeSetterBiConsumers.put(
			"verifiedDate",
			(BiConsumer<CollectionSetLink, Date>)
				CollectionSetLink::setVerifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCollectionSetLinkId() {
		return _collectionSetLinkId;
	}

	@Override
	public void setCollectionSetLinkId(long collectionSetLinkId) {
		_collectionSetLinkId = collectionSetLinkId;
	}

	@Override
	public long getDataCollectionId() {
		return _dataCollectionId;
	}

	@Override
	public void setDataCollectionId(long dataCollectionId) {
		_columnBitmask |= DATACOLLECTIONID_COLUMN_BITMASK;

		if (!_setOriginalDataCollectionId) {
			_setOriginalDataCollectionId = true;

			_originalDataCollectionId = _dataCollectionId;
		}

		_dataCollectionId = dataCollectionId;
	}

	public long getOriginalDataCollectionId() {
		return _originalDataCollectionId;
	}

	@Override
	public long getDataSetId() {
		return _dataSetId;
	}

	@Override
	public void setDataSetId(long dataSetId) {
		_columnBitmask |= DATASETID_COLUMN_BITMASK;

		if (!_setOriginalDataSetId) {
			_setOriginalDataSetId = true;

			_originalDataSetId = _dataSetId;
		}

		_dataSetId = dataSetId;
	}

	public long getOriginalDataSetId() {
		return _originalDataSetId;
	}

	@Override
	public int getOrder() {
		return _order;
	}

	@Override
	public void setOrder(int order) {
		_order = order;
	}

	@Override
	public boolean getCommentable() {
		return _commentable;
	}

	@Override
	public boolean isCommentable() {
		return _commentable;
	}

	@Override
	public void setCommentable(boolean commentable) {
		_commentable = commentable;
	}

	@Override
	public boolean getVerifiable() {
		return _verifiable;
	}

	@Override
	public boolean isVerifiable() {
		return _verifiable;
	}

	@Override
	public void setVerifiable(boolean verifiable) {
		_verifiable = verifiable;
	}

	@Override
	public boolean getFreezable() {
		return _freezable;
	}

	@Override
	public boolean isFreezable() {
		return _freezable;
	}

	@Override
	public void setFreezable(boolean freezable) {
		_freezable = freezable;
	}

	@Override
	public boolean getFreezed() {
		return _freezed;
	}

	@Override
	public boolean isFreezed() {
		return _freezed;
	}

	@Override
	public void setFreezed(boolean freezed) {
		_freezed = freezed;
	}

	@Override
	public long getFreezedUserId() {
		return _freezedUserId;
	}

	@Override
	public void setFreezedUserId(long freezedUserId) {
		_freezedUserId = freezedUserId;
	}

	@Override
	public String getFreezedUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getFreezedUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setFreezedUserUuid(String freezedUserUuid) {
	}

	@Override
	public String getFreezedUserName() {
		if (_freezedUserName == null) {
			return "";
		}
		else {
			return _freezedUserName;
		}
	}

	@Override
	public void setFreezedUserName(String freezedUserName) {
		_freezedUserName = freezedUserName;
	}

	@Override
	public Date getFreezedDate() {
		return _freezedDate;
	}

	@Override
	public void setFreezedDate(Date freezedDate) {
		_freezedDate = freezedDate;
	}

	@Override
	public boolean getVerified() {
		return _verified;
	}

	@Override
	public boolean isVerified() {
		return _verified;
	}

	@Override
	public void setVerified(boolean verified) {
		_verified = verified;
	}

	@Override
	public long getVerifiedUserId() {
		return _verifiedUserId;
	}

	@Override
	public void setVerifiedUserId(long verifiedUserId) {
		_verifiedUserId = verifiedUserId;
	}

	@Override
	public String getVerifiedUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getVerifiedUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setVerifiedUserUuid(String verifiedUserUuid) {
	}

	@Override
	public String getVerifiedUserName() {
		if (_verifiedUserName == null) {
			return "";
		}
		else {
			return _verifiedUserName;
		}
	}

	@Override
	public void setVerifiedUserName(String verifiedUserName) {
		_verifiedUserName = verifiedUserName;
	}

	@Override
	public Date getVerifiedDate() {
		return _verifiedDate;
	}

	@Override
	public void setVerifiedDate(Date verifiedDate) {
		_verifiedDate = verifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CollectionSetLink.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CollectionSetLink toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CollectionSetLink>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CollectionSetLinkImpl collectionSetLinkImpl =
			new CollectionSetLinkImpl();

		collectionSetLinkImpl.setCompanyId(getCompanyId());
		collectionSetLinkImpl.setGroupId(getGroupId());
		collectionSetLinkImpl.setCollectionSetLinkId(getCollectionSetLinkId());
		collectionSetLinkImpl.setDataCollectionId(getDataCollectionId());
		collectionSetLinkImpl.setDataSetId(getDataSetId());
		collectionSetLinkImpl.setOrder(getOrder());
		collectionSetLinkImpl.setCommentable(isCommentable());
		collectionSetLinkImpl.setVerifiable(isVerifiable());
		collectionSetLinkImpl.setFreezable(isFreezable());
		collectionSetLinkImpl.setFreezed(isFreezed());
		collectionSetLinkImpl.setFreezedUserId(getFreezedUserId());
		collectionSetLinkImpl.setFreezedUserName(getFreezedUserName());
		collectionSetLinkImpl.setFreezedDate(getFreezedDate());
		collectionSetLinkImpl.setVerified(isVerified());
		collectionSetLinkImpl.setVerifiedUserId(getVerifiedUserId());
		collectionSetLinkImpl.setVerifiedUserName(getVerifiedUserName());
		collectionSetLinkImpl.setVerifiedDate(getVerifiedDate());

		collectionSetLinkImpl.resetOriginalValues();

		return collectionSetLinkImpl;
	}

	@Override
	public int compareTo(CollectionSetLink collectionSetLink) {
		long primaryKey = collectionSetLink.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CollectionSetLink)) {
			return false;
		}

		CollectionSetLink collectionSetLink = (CollectionSetLink)object;

		long primaryKey = collectionSetLink.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalDataCollectionId = _dataCollectionId;

		_setOriginalDataCollectionId = false;

		_originalDataSetId = _dataSetId;

		_setOriginalDataSetId = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CollectionSetLink> toCacheModel() {
		CollectionSetLinkCacheModel collectionSetLinkCacheModel =
			new CollectionSetLinkCacheModel();

		collectionSetLinkCacheModel.companyId = getCompanyId();

		collectionSetLinkCacheModel.groupId = getGroupId();

		collectionSetLinkCacheModel.collectionSetLinkId =
			getCollectionSetLinkId();

		collectionSetLinkCacheModel.dataCollectionId = getDataCollectionId();

		collectionSetLinkCacheModel.dataSetId = getDataSetId();

		collectionSetLinkCacheModel.order = getOrder();

		collectionSetLinkCacheModel.commentable = isCommentable();

		collectionSetLinkCacheModel.verifiable = isVerifiable();

		collectionSetLinkCacheModel.freezable = isFreezable();

		collectionSetLinkCacheModel.freezed = isFreezed();

		collectionSetLinkCacheModel.freezedUserId = getFreezedUserId();

		collectionSetLinkCacheModel.freezedUserName = getFreezedUserName();

		String freezedUserName = collectionSetLinkCacheModel.freezedUserName;

		if ((freezedUserName != null) && (freezedUserName.length() == 0)) {
			collectionSetLinkCacheModel.freezedUserName = null;
		}

		Date freezedDate = getFreezedDate();

		if (freezedDate != null) {
			collectionSetLinkCacheModel.freezedDate = freezedDate.getTime();
		}
		else {
			collectionSetLinkCacheModel.freezedDate = Long.MIN_VALUE;
		}

		collectionSetLinkCacheModel.verified = isVerified();

		collectionSetLinkCacheModel.verifiedUserId = getVerifiedUserId();

		collectionSetLinkCacheModel.verifiedUserName = getVerifiedUserName();

		String verifiedUserName = collectionSetLinkCacheModel.verifiedUserName;

		if ((verifiedUserName != null) && (verifiedUserName.length() == 0)) {
			collectionSetLinkCacheModel.verifiedUserName = null;
		}

		Date verifiedDate = getVerifiedDate();

		if (verifiedDate != null) {
			collectionSetLinkCacheModel.verifiedDate = verifiedDate.getTime();
		}
		else {
			collectionSetLinkCacheModel.verifiedDate = Long.MIN_VALUE;
		}

		return collectionSetLinkCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CollectionSetLink, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CollectionSetLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CollectionSetLink, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(CollectionSetLink)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CollectionSetLink, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CollectionSetLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CollectionSetLink, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CollectionSetLink)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CollectionSetLink>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					CollectionSetLink.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _companyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _collectionSetLinkId;
	private long _dataCollectionId;
	private long _originalDataCollectionId;
	private boolean _setOriginalDataCollectionId;
	private long _dataSetId;
	private long _originalDataSetId;
	private boolean _setOriginalDataSetId;
	private int _order;
	private boolean _commentable;
	private boolean _verifiable;
	private boolean _freezable;
	private boolean _freezed;
	private long _freezedUserId;
	private String _freezedUserName;
	private Date _freezedDate;
	private boolean _verified;
	private long _verifiedUserId;
	private String _verifiedUserName;
	private Date _verifiedDate;
	private long _columnBitmask;
	private CollectionSetLink _escapedModel;

}