/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.sx.icecap.model.impl;

import com.sx.icecap.model.CollectionSetLink;
import com.sx.icecap.service.CollectionSetLinkLocalServiceUtil;

/**
 * The extended model base implementation for the CollectionSetLink service. Represents a row in the &quot;SX_ICECAP_CollectionSetLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CollectionSetLinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CollectionSetLinkImpl
 * @see CollectionSetLink
 * @generated
 */
public abstract class CollectionSetLinkBaseImpl
	extends CollectionSetLinkModelImpl implements CollectionSetLink {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a collection set link model instance should use the <code>CollectionSetLink</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CollectionSetLinkLocalServiceUtil.addCollectionSetLink(this);
		}
		else {
			CollectionSetLinkLocalServiceUtil.updateCollectionSetLink(this);
		}
	}

}