/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.sx.icecap.model.impl;

import com.sx.icecap.model.DataType;
import com.sx.icecap.service.DataTypeLocalServiceUtil;

/**
 * The extended model base implementation for the DataType service. Represents a row in the &quot;SX_ICECAP_DataType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DataTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DataTypeImpl
 * @see DataType
 * @generated
 */
public abstract class DataTypeBaseImpl
	extends DataTypeModelImpl implements DataType {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a data type model instance should use the <code>DataType</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			DataTypeLocalServiceUtil.addDataType(this);
		}
		else {
			DataTypeLocalServiceUtil.updateDataType(this);
		}
	}

}