/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.sx.icecap.model.impl;

import com.sx.icecap.model.DataTypeStructure;
import com.sx.icecap.service.DataTypeStructureLocalServiceUtil;

/**
 * The extended model base implementation for the DataTypeStructure service. Represents a row in the &quot;SX_ICECAP_DataTypeStructure&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DataTypeStructureImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DataTypeStructureImpl
 * @see DataTypeStructure
 * @generated
 */
public abstract class DataTypeStructureBaseImpl
	extends DataTypeStructureModelImpl implements DataTypeStructure {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a data type structure model instance should use the <code>DataTypeStructure</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			DataTypeStructureLocalServiceUtil.addDataTypeStructure(this);
		}
		else {
			DataTypeStructureLocalServiceUtil.updateDataTypeStructure(this);
		}
	}

}