/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sx.icecap.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import com.sx.icecap.model.Parameter;
import com.sx.icecap.model.ParameterModel;
import com.sx.icecap.model.ParameterSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Parameter service. Represents a row in the &quot;SX_ICECAP_Parameter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ParameterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ParameterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ParameterImpl
 * @generated
 */
@JSON(strict = true)
public class ParameterModelImpl
	extends BaseModelImpl<Parameter> implements ParameterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a parameter model instance should use the <code>Parameter</code> interface instead.
	 */
	public static final String TABLE_NAME = "SX_ICECAP_Parameter";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"parameterId", Types.BIGINT},
		{"groupParameterId", Types.VARCHAR}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}, {"lastPublishDate", Types.TIMESTAMP},
		{"paramName", Types.VARCHAR}, {"paramVersion", Types.VARCHAR},
		{"paramType", Types.VARCHAR}, {"displayName", Types.VARCHAR},
		{"definition", Types.VARCHAR}, {"tooltip", Types.VARCHAR},
		{"synonyms", Types.VARCHAR}, {"typeProperties", Types.VARCHAR},
		{"standard", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("parameterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupParameterId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("paramName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("paramVersion", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("paramType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("displayName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("definition", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tooltip", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("synonyms", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("typeProperties", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("standard", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SX_ICECAP_Parameter (uuid_ VARCHAR(75) null,parameterId LONG not null primary key,groupParameterId VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,lastPublishDate DATE null,paramName VARCHAR(75) null,paramVersion VARCHAR(75) null,paramType VARCHAR(75) null,displayName STRING null,definition STRING null,tooltip STRING null,synonyms VARCHAR(75) null,typeProperties VARCHAR(75) null,standard BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table SX_ICECAP_Parameter";

	public static final String ORDER_BY_JPQL =
		" ORDER BY parameter.paramName ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SX_ICECAP_Parameter.paramName ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long PARAMNAME_COLUMN_BITMASK = 4L;

	public static final long PARAMVERSION_COLUMN_BITMASK = 8L;

	public static final long STATUS_COLUMN_BITMASK = 16L;

	public static final long USERID_COLUMN_BITMASK = 32L;

	public static final long UUID_COLUMN_BITMASK = 64L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Parameter toModel(ParameterSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Parameter model = new ParameterImpl();

		model.setUuid(soapModel.getUuid());
		model.setParameterId(soapModel.getParameterId());
		model.setGroupParameterId(soapModel.getGroupParameterId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setLastPublishDate(soapModel.getLastPublishDate());
		model.setParamName(soapModel.getParamName());
		model.setParamVersion(soapModel.getParamVersion());
		model.setParamType(soapModel.getParamType());
		model.setDisplayName(soapModel.getDisplayName());
		model.setDefinition(soapModel.getDefinition());
		model.setTooltip(soapModel.getTooltip());
		model.setSynonyms(soapModel.getSynonyms());
		model.setTypeProperties(soapModel.getTypeProperties());
		model.setStandard(soapModel.isStandard());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Parameter> toModels(ParameterSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Parameter> models = new ArrayList<Parameter>(soapModels.length);

		for (ParameterSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ParameterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _parameterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setParameterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _parameterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Parameter.class;
	}

	@Override
	public String getModelClassName() {
		return Parameter.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Parameter, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Parameter, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Parameter, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Parameter)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Parameter, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Parameter, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Parameter)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Parameter, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Parameter, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Parameter, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Parameter, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Parameter, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Parameter, Object>>();
		Map<String, BiConsumer<Parameter, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Parameter, ?>>();

		attributeGetterFunctions.put("uuid", Parameter::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Parameter, String>)Parameter::setUuid);
		attributeGetterFunctions.put("parameterId", Parameter::getParameterId);
		attributeSetterBiConsumers.put(
			"parameterId",
			(BiConsumer<Parameter, Long>)Parameter::setParameterId);
		attributeGetterFunctions.put(
			"groupParameterId", Parameter::getGroupParameterId);
		attributeSetterBiConsumers.put(
			"groupParameterId",
			(BiConsumer<Parameter, String>)Parameter::setGroupParameterId);
		attributeGetterFunctions.put("groupId", Parameter::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Parameter, Long>)Parameter::setGroupId);
		attributeGetterFunctions.put("companyId", Parameter::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Parameter, Long>)Parameter::setCompanyId);
		attributeGetterFunctions.put("userId", Parameter::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Parameter, Long>)Parameter::setUserId);
		attributeGetterFunctions.put("userName", Parameter::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Parameter, String>)Parameter::setUserName);
		attributeGetterFunctions.put("createDate", Parameter::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<Parameter, Date>)Parameter::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", Parameter::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Parameter, Date>)Parameter::setModifiedDate);
		attributeGetterFunctions.put("status", Parameter::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<Parameter, Integer>)Parameter::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", Parameter::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<Parameter, Long>)Parameter::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", Parameter::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<Parameter, String>)Parameter::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", Parameter::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<Parameter, Date>)Parameter::setStatusDate);
		attributeGetterFunctions.put(
			"lastPublishDate", Parameter::getLastPublishDate);
		attributeSetterBiConsumers.put(
			"lastPublishDate",
			(BiConsumer<Parameter, Date>)Parameter::setLastPublishDate);
		attributeGetterFunctions.put("paramName", Parameter::getParamName);
		attributeSetterBiConsumers.put(
			"paramName",
			(BiConsumer<Parameter, String>)Parameter::setParamName);
		attributeGetterFunctions.put(
			"paramVersion", Parameter::getParamVersion);
		attributeSetterBiConsumers.put(
			"paramVersion",
			(BiConsumer<Parameter, String>)Parameter::setParamVersion);
		attributeGetterFunctions.put("paramType", Parameter::getParamType);
		attributeSetterBiConsumers.put(
			"paramType",
			(BiConsumer<Parameter, String>)Parameter::setParamType);
		attributeGetterFunctions.put("displayName", Parameter::getDisplayName);
		attributeSetterBiConsumers.put(
			"displayName",
			(BiConsumer<Parameter, String>)Parameter::setDisplayName);
		attributeGetterFunctions.put("definition", Parameter::getDefinition);
		attributeSetterBiConsumers.put(
			"definition",
			(BiConsumer<Parameter, String>)Parameter::setDefinition);
		attributeGetterFunctions.put("tooltip", Parameter::getTooltip);
		attributeSetterBiConsumers.put(
			"tooltip", (BiConsumer<Parameter, String>)Parameter::setTooltip);
		attributeGetterFunctions.put("synonyms", Parameter::getSynonyms);
		attributeSetterBiConsumers.put(
			"synonyms", (BiConsumer<Parameter, String>)Parameter::setSynonyms);
		attributeGetterFunctions.put(
			"typeProperties", Parameter::getTypeProperties);
		attributeSetterBiConsumers.put(
			"typeProperties",
			(BiConsumer<Parameter, String>)Parameter::setTypeProperties);
		attributeGetterFunctions.put("standard", Parameter::getStandard);
		attributeSetterBiConsumers.put(
			"standard", (BiConsumer<Parameter, Boolean>)Parameter::setStandard);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getParameterId() {
		return _parameterId;
	}

	@Override
	public void setParameterId(long parameterId) {
		_parameterId = parameterId;
	}

	@JSON
	@Override
	public String getGroupParameterId() {
		if (_groupParameterId == null) {
			return "";
		}
		else {
			return _groupParameterId;
		}
	}

	@Override
	public void setGroupParameterId(String groupParameterId) {
		_groupParameterId = groupParameterId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		_lastPublishDate = lastPublishDate;
	}

	@JSON
	@Override
	public String getParamName() {
		if (_paramName == null) {
			return "";
		}
		else {
			return _paramName;
		}
	}

	@Override
	public void setParamName(String paramName) {
		_columnBitmask = -1L;

		if (_originalParamName == null) {
			_originalParamName = _paramName;
		}

		_paramName = paramName;
	}

	public String getOriginalParamName() {
		return GetterUtil.getString(_originalParamName);
	}

	@JSON
	@Override
	public String getParamVersion() {
		if (_paramVersion == null) {
			return "";
		}
		else {
			return _paramVersion;
		}
	}

	@Override
	public void setParamVersion(String paramVersion) {
		_columnBitmask |= PARAMVERSION_COLUMN_BITMASK;

		if (_originalParamVersion == null) {
			_originalParamVersion = _paramVersion;
		}

		_paramVersion = paramVersion;
	}

	public String getOriginalParamVersion() {
		return GetterUtil.getString(_originalParamVersion);
	}

	@JSON
	@Override
	public String getParamType() {
		if (_paramType == null) {
			return "";
		}
		else {
			return _paramType;
		}
	}

	@Override
	public void setParamType(String paramType) {
		_paramType = paramType;
	}

	@JSON
	@Override
	public String getDisplayName() {
		if (_displayName == null) {
			return "";
		}
		else {
			return _displayName;
		}
	}

	@Override
	public String getDisplayName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDisplayName(languageId);
	}

	@Override
	public String getDisplayName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDisplayName(languageId, useDefault);
	}

	@Override
	public String getDisplayName(String languageId) {
		return LocalizationUtil.getLocalization(getDisplayName(), languageId);
	}

	@Override
	public String getDisplayName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getDisplayName(), languageId, useDefault);
	}

	@Override
	public String getDisplayNameCurrentLanguageId() {
		return _displayNameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDisplayNameCurrentValue() {
		Locale locale = getLocale(_displayNameCurrentLanguageId);

		return getDisplayName(locale);
	}

	@Override
	public Map<Locale, String> getDisplayNameMap() {
		return LocalizationUtil.getLocalizationMap(getDisplayName());
	}

	@Override
	public void setDisplayName(String displayName) {
		_displayName = displayName;
	}

	@Override
	public void setDisplayName(String displayName, Locale locale) {
		setDisplayName(displayName, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDisplayName(
		String displayName, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(displayName)) {
			setDisplayName(
				LocalizationUtil.updateLocalization(
					getDisplayName(), "DisplayName", displayName, languageId,
					defaultLanguageId));
		}
		else {
			setDisplayName(
				LocalizationUtil.removeLocalization(
					getDisplayName(), "DisplayName", languageId));
		}
	}

	@Override
	public void setDisplayNameCurrentLanguageId(String languageId) {
		_displayNameCurrentLanguageId = languageId;
	}

	@Override
	public void setDisplayNameMap(Map<Locale, String> displayNameMap) {
		setDisplayNameMap(displayNameMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDisplayNameMap(
		Map<Locale, String> displayNameMap, Locale defaultLocale) {

		if (displayNameMap == null) {
			return;
		}

		setDisplayName(
			LocalizationUtil.updateLocalization(
				displayNameMap, getDisplayName(), "DisplayName",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getDefinition() {
		if (_definition == null) {
			return "";
		}
		else {
			return _definition;
		}
	}

	@Override
	public String getDefinition(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDefinition(languageId);
	}

	@Override
	public String getDefinition(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDefinition(languageId, useDefault);
	}

	@Override
	public String getDefinition(String languageId) {
		return LocalizationUtil.getLocalization(getDefinition(), languageId);
	}

	@Override
	public String getDefinition(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getDefinition(), languageId, useDefault);
	}

	@Override
	public String getDefinitionCurrentLanguageId() {
		return _definitionCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDefinitionCurrentValue() {
		Locale locale = getLocale(_definitionCurrentLanguageId);

		return getDefinition(locale);
	}

	@Override
	public Map<Locale, String> getDefinitionMap() {
		return LocalizationUtil.getLocalizationMap(getDefinition());
	}

	@Override
	public void setDefinition(String definition) {
		_definition = definition;
	}

	@Override
	public void setDefinition(String definition, Locale locale) {
		setDefinition(definition, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDefinition(
		String definition, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(definition)) {
			setDefinition(
				LocalizationUtil.updateLocalization(
					getDefinition(), "Definition", definition, languageId,
					defaultLanguageId));
		}
		else {
			setDefinition(
				LocalizationUtil.removeLocalization(
					getDefinition(), "Definition", languageId));
		}
	}

	@Override
	public void setDefinitionCurrentLanguageId(String languageId) {
		_definitionCurrentLanguageId = languageId;
	}

	@Override
	public void setDefinitionMap(Map<Locale, String> definitionMap) {
		setDefinitionMap(definitionMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDefinitionMap(
		Map<Locale, String> definitionMap, Locale defaultLocale) {

		if (definitionMap == null) {
			return;
		}

		setDefinition(
			LocalizationUtil.updateLocalization(
				definitionMap, getDefinition(), "Definition",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getTooltip() {
		if (_tooltip == null) {
			return "";
		}
		else {
			return _tooltip;
		}
	}

	@Override
	public String getTooltip(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTooltip(languageId);
	}

	@Override
	public String getTooltip(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTooltip(languageId, useDefault);
	}

	@Override
	public String getTooltip(String languageId) {
		return LocalizationUtil.getLocalization(getTooltip(), languageId);
	}

	@Override
	public String getTooltip(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getTooltip(), languageId, useDefault);
	}

	@Override
	public String getTooltipCurrentLanguageId() {
		return _tooltipCurrentLanguageId;
	}

	@JSON
	@Override
	public String getTooltipCurrentValue() {
		Locale locale = getLocale(_tooltipCurrentLanguageId);

		return getTooltip(locale);
	}

	@Override
	public Map<Locale, String> getTooltipMap() {
		return LocalizationUtil.getLocalizationMap(getTooltip());
	}

	@Override
	public void setTooltip(String tooltip) {
		_tooltip = tooltip;
	}

	@Override
	public void setTooltip(String tooltip, Locale locale) {
		setTooltip(tooltip, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTooltip(
		String tooltip, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(tooltip)) {
			setTooltip(
				LocalizationUtil.updateLocalization(
					getTooltip(), "Tooltip", tooltip, languageId,
					defaultLanguageId));
		}
		else {
			setTooltip(
				LocalizationUtil.removeLocalization(
					getTooltip(), "Tooltip", languageId));
		}
	}

	@Override
	public void setTooltipCurrentLanguageId(String languageId) {
		_tooltipCurrentLanguageId = languageId;
	}

	@Override
	public void setTooltipMap(Map<Locale, String> tooltipMap) {
		setTooltipMap(tooltipMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTooltipMap(
		Map<Locale, String> tooltipMap, Locale defaultLocale) {

		if (tooltipMap == null) {
			return;
		}

		setTooltip(
			LocalizationUtil.updateLocalization(
				tooltipMap, getTooltip(), "Tooltip",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getSynonyms() {
		if (_synonyms == null) {
			return "";
		}
		else {
			return _synonyms;
		}
	}

	@Override
	public void setSynonyms(String synonyms) {
		_synonyms = synonyms;
	}

	@JSON
	@Override
	public String getTypeProperties() {
		if (_typeProperties == null) {
			return "";
		}
		else {
			return _typeProperties;
		}
	}

	@Override
	public void setTypeProperties(String typeProperties) {
		_typeProperties = typeProperties;
	}

	@JSON
	@Override
	public boolean getStandard() {
		return _standard;
	}

	@JSON
	@Override
	public boolean isStandard() {
		return _standard;
	}

	@Override
	public void setStandard(boolean standard) {
		_standard = standard;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Parameter.class.getName()));
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {

		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if (Validator.isNotNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException noSuchModelException) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler =
					com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
						getTrashHandler(
							trashHandler.getContainerModelClassName(
								containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(
					containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
			getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if ((trashHandler == null) ||
			Validator.isNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			return false;
		}

		try {
			ContainerModel containerModel =
				trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception exception) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Parameter.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> displayNameMap = getDisplayNameMap();

		for (Map.Entry<Locale, String> entry : displayNameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> definitionMap = getDefinitionMap();

		for (Map.Entry<Locale, String> entry : definitionMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> tooltipMap = getTooltipMap();

		for (Map.Entry<Locale, String> entry : tooltipMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getDisplayName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			Parameter.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String displayName = getDisplayName(defaultLocale);

		if (Validator.isNull(displayName)) {
			setDisplayName(
				getDisplayName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDisplayName(
				getDisplayName(defaultLocale), defaultLocale, defaultLocale);
		}

		String definition = getDefinition(defaultLocale);

		if (Validator.isNull(definition)) {
			setDefinition(getDefinition(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDefinition(
				getDefinition(defaultLocale), defaultLocale, defaultLocale);
		}

		String tooltip = getTooltip(defaultLocale);

		if (Validator.isNull(tooltip)) {
			setTooltip(getTooltip(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setTooltip(getTooltip(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public Parameter toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Parameter>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ParameterImpl parameterImpl = new ParameterImpl();

		parameterImpl.setUuid(getUuid());
		parameterImpl.setParameterId(getParameterId());
		parameterImpl.setGroupParameterId(getGroupParameterId());
		parameterImpl.setGroupId(getGroupId());
		parameterImpl.setCompanyId(getCompanyId());
		parameterImpl.setUserId(getUserId());
		parameterImpl.setUserName(getUserName());
		parameterImpl.setCreateDate(getCreateDate());
		parameterImpl.setModifiedDate(getModifiedDate());
		parameterImpl.setStatus(getStatus());
		parameterImpl.setStatusByUserId(getStatusByUserId());
		parameterImpl.setStatusByUserName(getStatusByUserName());
		parameterImpl.setStatusDate(getStatusDate());
		parameterImpl.setLastPublishDate(getLastPublishDate());
		parameterImpl.setParamName(getParamName());
		parameterImpl.setParamVersion(getParamVersion());
		parameterImpl.setParamType(getParamType());
		parameterImpl.setDisplayName(getDisplayName());
		parameterImpl.setDefinition(getDefinition());
		parameterImpl.setTooltip(getTooltip());
		parameterImpl.setSynonyms(getSynonyms());
		parameterImpl.setTypeProperties(getTypeProperties());
		parameterImpl.setStandard(isStandard());

		parameterImpl.resetOriginalValues();

		return parameterImpl;
	}

	@Override
	public int compareTo(Parameter parameter) {
		int value = 0;

		value = getParamName().compareTo(parameter.getParamName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Parameter)) {
			return false;
		}

		Parameter parameter = (Parameter)object;

		long primaryKey = parameter.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalUserId = _userId;

		_setOriginalUserId = false;

		_setModifiedDate = false;
		_originalStatus = _status;

		_setOriginalStatus = false;

		_originalParamName = _paramName;

		_originalParamVersion = _paramVersion;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Parameter> toCacheModel() {
		ParameterCacheModel parameterCacheModel = new ParameterCacheModel();

		parameterCacheModel.uuid = getUuid();

		String uuid = parameterCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			parameterCacheModel.uuid = null;
		}

		parameterCacheModel.parameterId = getParameterId();

		parameterCacheModel.groupParameterId = getGroupParameterId();

		String groupParameterId = parameterCacheModel.groupParameterId;

		if ((groupParameterId != null) && (groupParameterId.length() == 0)) {
			parameterCacheModel.groupParameterId = null;
		}

		parameterCacheModel.groupId = getGroupId();

		parameterCacheModel.companyId = getCompanyId();

		parameterCacheModel.userId = getUserId();

		parameterCacheModel.userName = getUserName();

		String userName = parameterCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			parameterCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			parameterCacheModel.createDate = createDate.getTime();
		}
		else {
			parameterCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			parameterCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			parameterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		parameterCacheModel.status = getStatus();

		parameterCacheModel.statusByUserId = getStatusByUserId();

		parameterCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = parameterCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			parameterCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			parameterCacheModel.statusDate = statusDate.getTime();
		}
		else {
			parameterCacheModel.statusDate = Long.MIN_VALUE;
		}

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			parameterCacheModel.lastPublishDate = lastPublishDate.getTime();
		}
		else {
			parameterCacheModel.lastPublishDate = Long.MIN_VALUE;
		}

		parameterCacheModel.paramName = getParamName();

		String paramName = parameterCacheModel.paramName;

		if ((paramName != null) && (paramName.length() == 0)) {
			parameterCacheModel.paramName = null;
		}

		parameterCacheModel.paramVersion = getParamVersion();

		String paramVersion = parameterCacheModel.paramVersion;

		if ((paramVersion != null) && (paramVersion.length() == 0)) {
			parameterCacheModel.paramVersion = null;
		}

		parameterCacheModel.paramType = getParamType();

		String paramType = parameterCacheModel.paramType;

		if ((paramType != null) && (paramType.length() == 0)) {
			parameterCacheModel.paramType = null;
		}

		parameterCacheModel.displayName = getDisplayName();

		String displayName = parameterCacheModel.displayName;

		if ((displayName != null) && (displayName.length() == 0)) {
			parameterCacheModel.displayName = null;
		}

		parameterCacheModel.definition = getDefinition();

		String definition = parameterCacheModel.definition;

		if ((definition != null) && (definition.length() == 0)) {
			parameterCacheModel.definition = null;
		}

		parameterCacheModel.tooltip = getTooltip();

		String tooltip = parameterCacheModel.tooltip;

		if ((tooltip != null) && (tooltip.length() == 0)) {
			parameterCacheModel.tooltip = null;
		}

		parameterCacheModel.synonyms = getSynonyms();

		String synonyms = parameterCacheModel.synonyms;

		if ((synonyms != null) && (synonyms.length() == 0)) {
			parameterCacheModel.synonyms = null;
		}

		parameterCacheModel.typeProperties = getTypeProperties();

		String typeProperties = parameterCacheModel.typeProperties;

		if ((typeProperties != null) && (typeProperties.length() == 0)) {
			parameterCacheModel.typeProperties = null;
		}

		parameterCacheModel.standard = isStandard();

		return parameterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Parameter, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Parameter, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Parameter, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Parameter)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Parameter, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Parameter, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Parameter, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Parameter)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Parameter>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Parameter.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _parameterId;
	private String _groupParameterId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private Date _lastPublishDate;
	private String _paramName;
	private String _originalParamName;
	private String _paramVersion;
	private String _originalParamVersion;
	private String _paramType;
	private String _displayName;
	private String _displayNameCurrentLanguageId;
	private String _definition;
	private String _definitionCurrentLanguageId;
	private String _tooltip;
	private String _tooltipCurrentLanguageId;
	private String _synonyms;
	private String _typeProperties;
	private boolean _standard;
	private long _columnBitmask;
	private Parameter _escapedModel;

}