/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sx.icecap.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.sx.icecap.model.SetTypeLink;
import com.sx.icecap.model.SetTypeLinkModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SetTypeLink service. Represents a row in the &quot;SX_ICECAP_SetTypeLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SetTypeLinkModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SetTypeLinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SetTypeLinkImpl
 * @generated
 */
public class SetTypeLinkModelImpl
	extends BaseModelImpl<SetTypeLink> implements SetTypeLinkModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a set type link model instance should use the <code>SetTypeLink</code> interface instead.
	 */
	public static final String TABLE_NAME = "SX_ICECAP_SetTypeLink";

	public static final Object[][] TABLE_COLUMNS = {
		{"setTypeLinkId", Types.BIGINT}, {"dataSetId", Types.BIGINT},
		{"dataSet", Types.BIGINT}, {"dataTypeId", Types.BIGINT},
		{"dataType", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("setTypeLinkId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataSetId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataSet", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataType", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SX_ICECAP_SetTypeLink (setTypeLinkId LONG not null primary key,dataSetId LONG,dataSet LONG,dataTypeId LONG,dataType VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table SX_ICECAP_SetTypeLink";

	public static final String ORDER_BY_JPQL =
		" ORDER BY setTypeLink.setTypeLinkId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SX_ICECAP_SetTypeLink.setTypeLinkId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long DATASETID_COLUMN_BITMASK = 1L;

	public static final long DATATYPEID_COLUMN_BITMASK = 2L;

	public static final long SETTYPELINKID_COLUMN_BITMASK = 4L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public SetTypeLinkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _setTypeLinkId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSetTypeLinkId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _setTypeLinkId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SetTypeLink.class;
	}

	@Override
	public String getModelClassName() {
		return SetTypeLink.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SetTypeLink, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SetTypeLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SetTypeLink, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SetTypeLink)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SetTypeLink, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SetTypeLink, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SetTypeLink)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SetTypeLink, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SetTypeLink, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<SetTypeLink, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SetTypeLink, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SetTypeLink, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<SetTypeLink, Object>>();
		Map<String, BiConsumer<SetTypeLink, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<SetTypeLink, ?>>();

		attributeGetterFunctions.put(
			"setTypeLinkId", SetTypeLink::getSetTypeLinkId);
		attributeSetterBiConsumers.put(
			"setTypeLinkId",
			(BiConsumer<SetTypeLink, Long>)SetTypeLink::setSetTypeLinkId);
		attributeGetterFunctions.put("dataSetId", SetTypeLink::getDataSetId);
		attributeSetterBiConsumers.put(
			"dataSetId",
			(BiConsumer<SetTypeLink, Long>)SetTypeLink::setDataSetId);
		attributeGetterFunctions.put("dataSet", SetTypeLink::getDataSet);
		attributeSetterBiConsumers.put(
			"dataSet", (BiConsumer<SetTypeLink, Long>)SetTypeLink::setDataSet);
		attributeGetterFunctions.put("dataTypeId", SetTypeLink::getDataTypeId);
		attributeSetterBiConsumers.put(
			"dataTypeId",
			(BiConsumer<SetTypeLink, Long>)SetTypeLink::setDataTypeId);
		attributeGetterFunctions.put("dataType", SetTypeLink::getDataType);
		attributeSetterBiConsumers.put(
			"dataType",
			(BiConsumer<SetTypeLink, String>)SetTypeLink::setDataType);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getSetTypeLinkId() {
		return _setTypeLinkId;
	}

	@Override
	public void setSetTypeLinkId(long setTypeLinkId) {
		_setTypeLinkId = setTypeLinkId;
	}

	@Override
	public long getDataSetId() {
		return _dataSetId;
	}

	@Override
	public void setDataSetId(long dataSetId) {
		_columnBitmask |= DATASETID_COLUMN_BITMASK;

		if (!_setOriginalDataSetId) {
			_setOriginalDataSetId = true;

			_originalDataSetId = _dataSetId;
		}

		_dataSetId = dataSetId;
	}

	public long getOriginalDataSetId() {
		return _originalDataSetId;
	}

	@Override
	public long getDataSet() {
		return _dataSet;
	}

	@Override
	public void setDataSet(long dataSet) {
		_dataSet = dataSet;
	}

	@Override
	public long getDataTypeId() {
		return _dataTypeId;
	}

	@Override
	public void setDataTypeId(long dataTypeId) {
		_columnBitmask |= DATATYPEID_COLUMN_BITMASK;

		if (!_setOriginalDataTypeId) {
			_setOriginalDataTypeId = true;

			_originalDataTypeId = _dataTypeId;
		}

		_dataTypeId = dataTypeId;
	}

	public long getOriginalDataTypeId() {
		return _originalDataTypeId;
	}

	@Override
	public String getDataType() {
		if (_dataType == null) {
			return "";
		}
		else {
			return _dataType;
		}
	}

	@Override
	public void setDataType(String dataType) {
		_dataType = dataType;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, SetTypeLink.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SetTypeLink toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SetTypeLink>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SetTypeLinkImpl setTypeLinkImpl = new SetTypeLinkImpl();

		setTypeLinkImpl.setSetTypeLinkId(getSetTypeLinkId());
		setTypeLinkImpl.setDataSetId(getDataSetId());
		setTypeLinkImpl.setDataSet(getDataSet());
		setTypeLinkImpl.setDataTypeId(getDataTypeId());
		setTypeLinkImpl.setDataType(getDataType());

		setTypeLinkImpl.resetOriginalValues();

		return setTypeLinkImpl;
	}

	@Override
	public int compareTo(SetTypeLink setTypeLink) {
		long primaryKey = setTypeLink.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SetTypeLink)) {
			return false;
		}

		SetTypeLink setTypeLink = (SetTypeLink)object;

		long primaryKey = setTypeLink.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalDataSetId = _dataSetId;

		_setOriginalDataSetId = false;

		_originalDataTypeId = _dataTypeId;

		_setOriginalDataTypeId = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SetTypeLink> toCacheModel() {
		SetTypeLinkCacheModel setTypeLinkCacheModel =
			new SetTypeLinkCacheModel();

		setTypeLinkCacheModel.setTypeLinkId = getSetTypeLinkId();

		setTypeLinkCacheModel.dataSetId = getDataSetId();

		setTypeLinkCacheModel.dataSet = getDataSet();

		setTypeLinkCacheModel.dataTypeId = getDataTypeId();

		setTypeLinkCacheModel.dataType = getDataType();

		String dataType = setTypeLinkCacheModel.dataType;

		if ((dataType != null) && (dataType.length() == 0)) {
			setTypeLinkCacheModel.dataType = null;
		}

		return setTypeLinkCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SetTypeLink, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SetTypeLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SetTypeLink, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((SetTypeLink)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SetTypeLink, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SetTypeLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SetTypeLink, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((SetTypeLink)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SetTypeLink>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SetTypeLink.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _setTypeLinkId;
	private long _dataSetId;
	private long _originalDataSetId;
	private boolean _setOriginalDataSetId;
	private long _dataSet;
	private long _dataTypeId;
	private long _originalDataTypeId;
	private boolean _setOriginalDataTypeId;
	private String _dataType;
	private long _columnBitmask;
	private SetTypeLink _escapedModel;

}