/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sx.icecap.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.sx.icecap.model.TypeParamLink;
import com.sx.icecap.model.TypeParamLinkModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TypeParamLink service. Represents a row in the &quot;SX_ICECAP_TypeParamLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TypeParamLinkModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TypeParamLinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TypeParamLinkImpl
 * @generated
 */
public class TypeParamLinkModelImpl
	extends BaseModelImpl<TypeParamLink> implements TypeParamLinkModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a type param link model instance should use the <code>TypeParamLink</code> interface instead.
	 */
	public static final String TABLE_NAME = "SX_ICECAP_TypeParamLink";

	public static final Object[][] TABLE_COLUMNS = {
		{"typeParamLinkId", Types.BIGINT}, {"dataTypeId", Types.BIGINT},
		{"dataType", Types.BIGINT}, {"paramId", Types.BIGINT},
		{"param", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("typeParamLinkId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataType", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("paramId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("param", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SX_ICECAP_TypeParamLink (typeParamLinkId LONG not null primary key,dataTypeId LONG,dataType LONG,paramId LONG,param VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table SX_ICECAP_TypeParamLink";

	public static final String ORDER_BY_JPQL =
		" ORDER BY typeParamLink.typeParamLinkId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SX_ICECAP_TypeParamLink.typeParamLinkId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long DATATYPEID_COLUMN_BITMASK = 1L;

	public static final long PARAMID_COLUMN_BITMASK = 2L;

	public static final long TYPEPARAMLINKID_COLUMN_BITMASK = 4L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public TypeParamLinkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _typeParamLinkId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTypeParamLinkId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _typeParamLinkId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TypeParamLink.class;
	}

	@Override
	public String getModelClassName() {
		return TypeParamLink.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TypeParamLink, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TypeParamLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TypeParamLink, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TypeParamLink)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TypeParamLink, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TypeParamLink, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TypeParamLink)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TypeParamLink, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TypeParamLink, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<TypeParamLink, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TypeParamLink, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TypeParamLink, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<TypeParamLink, Object>>();
		Map<String, BiConsumer<TypeParamLink, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<TypeParamLink, ?>>();

		attributeGetterFunctions.put(
			"typeParamLinkId", TypeParamLink::getTypeParamLinkId);
		attributeSetterBiConsumers.put(
			"typeParamLinkId",
			(BiConsumer<TypeParamLink, Long>)TypeParamLink::setTypeParamLinkId);
		attributeGetterFunctions.put(
			"dataTypeId", TypeParamLink::getDataTypeId);
		attributeSetterBiConsumers.put(
			"dataTypeId",
			(BiConsumer<TypeParamLink, Long>)TypeParamLink::setDataTypeId);
		attributeGetterFunctions.put("dataType", TypeParamLink::getDataType);
		attributeSetterBiConsumers.put(
			"dataType",
			(BiConsumer<TypeParamLink, Long>)TypeParamLink::setDataType);
		attributeGetterFunctions.put("paramId", TypeParamLink::getParamId);
		attributeSetterBiConsumers.put(
			"paramId",
			(BiConsumer<TypeParamLink, Long>)TypeParamLink::setParamId);
		attributeGetterFunctions.put("param", TypeParamLink::getParam);
		attributeSetterBiConsumers.put(
			"param",
			(BiConsumer<TypeParamLink, String>)TypeParamLink::setParam);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getTypeParamLinkId() {
		return _typeParamLinkId;
	}

	@Override
	public void setTypeParamLinkId(long typeParamLinkId) {
		_typeParamLinkId = typeParamLinkId;
	}

	@Override
	public long getDataTypeId() {
		return _dataTypeId;
	}

	@Override
	public void setDataTypeId(long dataTypeId) {
		_columnBitmask |= DATATYPEID_COLUMN_BITMASK;

		if (!_setOriginalDataTypeId) {
			_setOriginalDataTypeId = true;

			_originalDataTypeId = _dataTypeId;
		}

		_dataTypeId = dataTypeId;
	}

	public long getOriginalDataTypeId() {
		return _originalDataTypeId;
	}

	@Override
	public long getDataType() {
		return _dataType;
	}

	@Override
	public void setDataType(long dataType) {
		_dataType = dataType;
	}

	@Override
	public long getParamId() {
		return _paramId;
	}

	@Override
	public void setParamId(long paramId) {
		_columnBitmask |= PARAMID_COLUMN_BITMASK;

		if (!_setOriginalParamId) {
			_setOriginalParamId = true;

			_originalParamId = _paramId;
		}

		_paramId = paramId;
	}

	public long getOriginalParamId() {
		return _originalParamId;
	}

	@Override
	public String getParam() {
		if (_param == null) {
			return "";
		}
		else {
			return _param;
		}
	}

	@Override
	public void setParam(String param) {
		_param = param;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, TypeParamLink.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TypeParamLink toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TypeParamLink>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TypeParamLinkImpl typeParamLinkImpl = new TypeParamLinkImpl();

		typeParamLinkImpl.setTypeParamLinkId(getTypeParamLinkId());
		typeParamLinkImpl.setDataTypeId(getDataTypeId());
		typeParamLinkImpl.setDataType(getDataType());
		typeParamLinkImpl.setParamId(getParamId());
		typeParamLinkImpl.setParam(getParam());

		typeParamLinkImpl.resetOriginalValues();

		return typeParamLinkImpl;
	}

	@Override
	public int compareTo(TypeParamLink typeParamLink) {
		long primaryKey = typeParamLink.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TypeParamLink)) {
			return false;
		}

		TypeParamLink typeParamLink = (TypeParamLink)object;

		long primaryKey = typeParamLink.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalDataTypeId = _dataTypeId;

		_setOriginalDataTypeId = false;

		_originalParamId = _paramId;

		_setOriginalParamId = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TypeParamLink> toCacheModel() {
		TypeParamLinkCacheModel typeParamLinkCacheModel =
			new TypeParamLinkCacheModel();

		typeParamLinkCacheModel.typeParamLinkId = getTypeParamLinkId();

		typeParamLinkCacheModel.dataTypeId = getDataTypeId();

		typeParamLinkCacheModel.dataType = getDataType();

		typeParamLinkCacheModel.paramId = getParamId();

		typeParamLinkCacheModel.param = getParam();

		String param = typeParamLinkCacheModel.param;

		if ((param != null) && (param.length() == 0)) {
			typeParamLinkCacheModel.param = null;
		}

		return typeParamLinkCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TypeParamLink, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TypeParamLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TypeParamLink, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((TypeParamLink)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TypeParamLink, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TypeParamLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TypeParamLink, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((TypeParamLink)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TypeParamLink>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					TypeParamLink.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _typeParamLinkId;
	private long _dataTypeId;
	private long _originalDataTypeId;
	private boolean _setOriginalDataTypeId;
	private long _dataType;
	private long _paramId;
	private long _originalParamId;
	private boolean _setOriginalParamId;
	private String _param;
	private long _columnBitmask;
	private TypeParamLink _escapedModel;

}